name: Benchmarks

on: [pull_request]

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUST_BACKTRACE: short
  RUSTUP_MAX_RETRIES: 10

jobs:
  bench-skylake-2x:
    needs: [tests]
    runs-on: [self-hosted, skylake-2x]
    steps:
      - uses: actions/checkout@v3.0.2

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          default: true

      - name: Run Benchmarks
        run: |
          bash scripts/ci.bash

    - name: Find Comment
      uses: peter-evans/find-comment@v2
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: Nexmark benchmark results

    - name: Create or update comment
      uses: peter-evans/create-or-update-comment@v2
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body-file: nexmark_comment.txt
        edit-mode: replace

    env:
      CI_MACHINE_TYPE: "skylake-2x"